<?php

namespace Adminka\Uis;

use Adminka\UisSync\Console\Commands\UisSync;
use Illuminate\Support\ServiceProvider;

class UisServiceProvider extends ServiceProvider
{

    public function boot()
    {
        $this->loadRoutesFrom(__DIR__ . "/../routes/web.php");
        $this->loadMigrationsFrom(__DIR__ . "/../database/migrations");
        $this->publishes([
            __DIR__ . "/../config/uis.php" => config_path("uis.php")
        ]);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
